### ISSUE TITLE
Add home button to sidebar

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/materialsdatabank#22]
We already have a welcome button that takes use to the welcome text. Would the home button just bring you to the search results for public dataset ( which is what you see when you first visit the site )?

**Comment by cjh1** [comment]
Or may be we should just change the default page to be the welcome page ( which would then be the home page ). Thoughts? @cryos @apryor6

**Comment by cryos** [comment]
I think I would make the welcome page the default, and that would clear this up, and give a landing page with some introduction.

**Comment by apryor6** [comment]
Either way is fine. My only concern was that there is a page that you cannot navigate to other than using "back" or accessing the index page again

**Comment by cjh1** [comment]
Fixed by #24
