### ISSUE TITLE
Consistent naming - HTML title versus page header vs repo

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/materialsdatabank#23]
We should resolve this today, as I went over slide content, if we use voting then the plural wins. It is materials science, so I would have thought materials data bank would be most appropriate. I see the title of my talk is also singular, resulting in a tie from online sources. Consistency is key, I suspect we can clear this up today.

**Comment by cjh1** [comment]
@cryos I have made it consistently "materials" for now

**Comment by cjh1** [comment]
We seem to have settled on "materials"
